# -*- coding: utf-8 -*-
"""Predicting Flower Types

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KrR0LGtcltQP7qb5WGDD1F9G7hn40TWY
"""

# Commented out IPython magic to ensure Python compatibility.
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
sns.set(style="white", color_codes=True)
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

path="/content/drive/MyDrive/Dataset/Iris.csv"
flower = pd.read_csv(path)
flower.head()

sns.FacetGrid(flower, hue="Species",height=6).map(plt.scatter, "PetalLengthCm", "SepalWidthCm").add_legend()

mapping = {'Iris-setosa': 0,'Iris-versicolor': 1,'Iris-virginica':2}
flower["Species"] = flower["Species"].map(mapping)

x = flower[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']].values
y = flower['Species'].values

model = LogisticRegression()
model.fit(x,y)
model.score(x,y)

expected = y
predicted = model.predict(x)
predicted

from sklearn import metrics
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

model = LogisticRegression(C=20,penalty='l2' )
model.fit(x,y)
model.score(x,y)